# Generated by Django 4.2.14 on 2024-07-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokemonTeam', '0004_rename_firsttype_pokemonteam_primarytype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonteam',
            name='image',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
