# Generated by Django 4.2.14 on 2024-07-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokemonTeam', '0002_rename_pokemon_pokemonteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonteam',
            name='firstType',
            field=models.CharField(default='hello', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemonteam',
            name='secondType',
            field=models.CharField(default='hello', max_length=60),
            preserve_default=False,
        ),
    ]
