# Generated by Django 4.2.14 on 2024-07-15 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PokemonTeam', '0003_pokemonteam_firsttype_pokemonteam_secondtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonteam',
            old_name='firstType',
            new_name='primaryType',
        ),
        migrations.RenameField(
            model_name='pokemonteam',
            old_name='secondType',
            new_name='secondaryType',
        ),
    ]
