# Generated by Django 4.2.14 on 2024-07-15 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PokemonTeam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pokemon',
            new_name='PokemonTeam',
        ),
    ]
